FROM node:18 AS builder

WORKDIR /usr/src/app

EXPOSE 5173

COPY .env ./
COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .

RUN npm run build

# Serve with Nginx
FROM nginx:latest
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
COPY nginx/default.prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
