# fly.toml app configuration file generated for dusted-frontend on 2025-05-15T16:52:32+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dusted-frontend'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  VITE_BACKEND_URL='https://dusted-backend.fly.dev'
  VITE_GOOGLE_CLIENT_ID='414597970054-0r5hefrjr4p34lpsgqdonoerhndp8hk5.apps.googleusercontent.com'
  VITE_GOOGLE_REDIRECT_URI='https://dustedfilm.com/auth/google/callback'

