services:
  #Frontend React + Vite
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: frontend
          target: /usr/src/app
    env_file:
      - .env.dev
    volumes:
      - ./backend/staticfiles:/usr/src/app/staticfiles

  #Backend Django
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: backend
          target: /usr/src/app
    env_file:
      - .env.dev
    depends_on:
      - db
    volumes:
      - ./backend/staticfiles:/usr/src/app/staticfiles

  #Postgre
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #Nginx
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/staticfiles:/usr/src/app/staticfiles

volumes:
  postgres_data:
