services:
  # Frontend (React served via Nginx inside dockerfile.prod)
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/dockerfile.prod
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./backend/staticfiles:/usr/src/app/staticfiles

  # Backend (Django)
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend/staticfiles:/usr/src/app/staticfiles

  # PostgreSQL Database
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #nginx:
  #  container_name: nginx
  #  image: nginx:latest
  #  ports:
  #    - "80:80"
  #  depends_on:
  #    - frontend
  #    - backend
  #  volumes:
  #    - frontend_dist:/usr/share/nginx/html
  #    - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
  #    - ./backend/staticfiles:/usr/src/app/staticfiles

volumes:
  postgres_data:
