services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: frontend
          target: /usr/src/app
    env_file:
      - .env

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: backend
          target: /usr/src/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
