services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: backend
          target: /usr/src/app
