services:
  - type: web
    name: django-backend
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: backend/dockerfile
    buildCommand: ""
    startCommand: ""
    buildContext: backend
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
