FROM python:3.10

# make it read-only files and reduce disk usage
ENV PYTHONDONTWRITEBYTECODE 1
# flush the console and log immediately
ENV PYTHONUNBUFFERED 1

EXPOSE 8000

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/entrypoint.sh
COPY . .

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

#CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]
