# Generated by Django 5.0.4 on 2025-04-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
