# Generated by Django 5.0.4 on 2025-04-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_watchlist_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='overview',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
