# Generated by Django 5.0.4 on 2025-04-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_watchlist_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
