# Generated by Django 5.0.4 on 2025-03-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie_id',
            field=models.IntegerField(default=0),
        ),
    ]
