# Generated by Django 5.0.4 on 2025-03-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
