# Generated by Django 5.0.4 on 2025-04-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_image_path_alter_review_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
