# Generated by Django 5.0.4 on 2025-04-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_rename_image_path_review_backdrop_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='poster_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
