# Generated by Django 5.0.4 on 2025-05-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_folder_review_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cast',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='review',
            name='genre_ids',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
