# Generated by Django 5.0.4 on 2025-03-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language_preference',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
