# Generated by Django 5.0.4 on 2025-03-29 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_language_preference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='language_preference',
            new_name='language',
        ),
    ]
